In [15]:
import requests
import pandas as pd

url_A = "https://www.clubefii.com.br/fundo_imobiliario_lista"
url_B = "https://www.clubefii.com.br/fundos_imobiliarios_ranking"
headers = {
    'User-Agent': 
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36'
        ' (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36'
}

In [16]:
request_A = requests.get(url_A, headers=headers)
if request_A.status_code == 200:
    table_A = pd.read_html(request_A.text, encoding='utf-8')[0]

In [17]:
request_B = requests.get(url_B, headers=headers)
if request_B.status_code == 200:
    table_B = pd.read_html(request_B.text, encoding='utf-8')[0]

In [18]:
# Replace comma by dots in both tables
table_A = table_A.replace(',', '.', regex=True)
table_B = table_B.replace(',', '.', regex=True)

# Replace N/D by 0 in both tables
table_A = table_A.replace('N/D', 0)
table_B = table_B.replace('N/D', 0)

# Remove 'R$' and '%'
table_A = table_A.replace(['R\$', '%'], '', regex=True)
table_B = table_B.replace(['R\$', '%'], '', regex=True)

# Remove date fields in table A
table_A = table_A.replace("\d{2}/\d{2}/\d{4} \d{2}:\d{2}:\d{2}", "", regex=True)

In [19]:
# Remove column A and B from table A
table_A = table_A.drop(['FEED', 'DATA IPO', 'VALOR IPO', 'RELATÓRIOS DE ANÁLISE'], axis=1)

# Remove column C and D from table B
table_B = table_B.drop(['NOME', 'FEED', 'VARIAÇÃO COTA  DESDE IPO', 'YIELD  1 MES'], axis=1)

In [20]:
# Merge table A and table B
merged_table = pd.merge(table_A, table_B)

# Display on screen
display (merged_table)

,CÓDIGO,NOME,VALOR COTA,SEGMENTO,ADMINISTRADOR,VARIAÇÃO COTA + PROVENTOS DESDE IPO,P/VPA,YIELD 12 MESES
0,AFHI11,AF Invest CRI,96.99 +0.42,Recebíveis Imobiliários,BTG PACTUAL,+25.56,101,13.58
1,AIEC11,Autonomy Edifícios Corporativos,70.96 +1.3,Lajes Comerciais,MAF,-6.44,75,12.70
2,ALZR11,Alianza Trust Renda Imobiliária,115.17 +0.6,Híbrido,BTG PACTUAL,+61.59,108,12.47
3,ARRI11,Átrio Reit Recebíveis Imobiliários,8.95 +0.34,Recebíveis Imobiliários,OLIVEIRA TRUST,+32.04,100,14.31
4,BARI11,Barigui Rendimentos,85.27 +1.75,Recebíveis Imobiliários,OLIVEIRA TRUST,+40.78,88,12.65
...,...,...,...,...,...,...,...,...
106,XPIN11,XP Industrial,80.71 +0.89,Logisticos,VÓRTX,+16.82,79,9.50
107,XPLG11,XP Log,114.11 +0.63,Logisticos,VÓRTX,+50.52,101,7.11
108,XPML11,XP Malls,105.30 +0.29,Shopping/Varejo,XP INVESTIMENTOS,+39.87,107,8.79
109,XPPR11,XP Properties,23.09 +0.83,Lajes Comerciais,VÓRTX,-58.29,32,11.04
110,XPSF11,XP Selection,8.01 -0.25,Fundo de Fundos,XP INVESTIMENTOS,+9.62,95,10.39

In [21]:
# Export merged table to CSV or Excel
#merged_table.to_csv('FII_Clube.csv', index=False)
merged_table.to_excel('FII_Clube.xlsx', index=False)